//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.outgoing_permission = new HashSet<outgoing_permission>();
        }
    
        public int client_id { get; set; }
        public string client_name { get; set; }
        public string client_phone { get; set; }
        public string client_fax { get; set; }
        public string client_mobile { get; set; }
        public string client_email { get; set; }
        public string client_website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outgoing_permission> outgoing_permission { get; set; }
    }
}
