//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class outgoing_permission
    {
        public int store_id { get; set; }
        public int client_id { get; set; }
        public string type_code { get; set; }
        public string outgoing_permission_no { get; set; }
        public Nullable<System.DateTime> outgoing_permission_date { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual client client { get; set; }
        public virtual store store { get; set; }
        public virtual type type { get; set; }
    }
}
