//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply_permission
    {
        public int store_id { get; set; }
        public int supplier_id { get; set; }
        public string type_code { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string supply_permission_no { get; set; }
        public Nullable<System.DateTime> supply_permission_date { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual store store { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual type type { get; set; }
    }
}
